### ISSUE TITLE
Crashes on way to many RSS links

### ISSUE THREAD

**Issue by Ryu945** [fent/feedme.js#12]
Example code crashes on way to many RSS links.  For example.

https://game-guide.fr/archive_jeu/world-of-warcraft/feed/

**Comment by fent** [comment]
Can I see an example of the code you used, or the type of error you got. I just tried parsing that feed and it was fine.

This is the code I used

```js
 https.get('https://game-guide.fr/archive_jeu/world-of-warcraft/feed/', function(res) {
   var parser = res.pipe(new FeedMe(true));
   parser.on('item', function(item) {
     console.log(item.title);
   });
   parser.on('end', done);
 });
```
