### ISSUE TITLE
Fails to parse some RSS2

### ISSUE THREAD

**Issue by dsheiko** [fent/feedme.js#13]
Here an example https://www.smashingmagazine.com/feed/
While e.g. this parsing algorithm https://github.com/Xstoudi/alduin/blob/master/src/app/js/util/feed-parser.ts processes it fine

**Comment by fent** [comment]
I tried parsing that feed, and it was fine. What type of error did you get?

This is the code I used

```js
 https.get('https://www.smashingmagazine.com/feed/', function(res) {
   var parser = res.pipe(new FeedMe(true));
   parser.on('item', function(item) {
     console.log(item.title);
   });
   parser.on('end', done);
 });
```

**Comment by dsheiko** [comment]
Opps, sorry - just found out that it's HTTPS and I was using http.get. Everything works fine. Again, sorry for troublling
