### ISSUE TITLE
TypeError: parser.close is not a function

### ISSUE THREAD

**Issue by rejhgadellaa** [fent/feedme.js#14]
I'm getting this error that causes nodejs to crash when feed type is nog recognized. The feed that causes this issue is:

https://www.dadapixel.blog/?format=rss

Output:

> Error: Feed type not recognized
>     at SAXStream.openf1 (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\feedme\lib\xmlfeedparser.js:106:28)
>     at emitOne (events.js:96:13)
>     at SAXStream.emit (events.js:188:7)
>     at Object.me._parser.(anonymous function) [as onopentag] (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:258:17)
>     at emit (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:640:35)
>     at emitNode (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:645:5)
>     at openTag (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:841:5)
>     at Object.write (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:1294:15)
>     at SAXStream.write (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:239:18)
>     at yoshi.write (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\feedme\lib\feedme.js:41:14)
> C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\feedme\lib\xmlfeedparser.js:107
>       parser.close();
>              ^
> 
> TypeError: parser.close is not a function
>     at SAXStream.openf1 (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\feedme\lib\xmlfeedparser.js:107:14)
>     at emitOne (events.js:96:13)
>     at SAXStream.emit (events.js:188:7)
>     at Object.me._parser.(anonymous function) [as onopentag] (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:258:17)
>     at emit (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:640:35)
>     at emitNode (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:645:5)
>     at openTag (C:\Data\Working\REJH_SVN\feedlr\src\nodejs\fdlr-reader\node_modules\sax\lib\sax.js:841:5)

**Comment by fent** [comment]
Weird, I'm trying the same file but not getting the error.

At first look, I thought it might be the comment element at the start, but it looks like the parser is avoiding that.

Hmmm, what version of `sax` is being installed?

**Comment by rejhgadellaa** [comment]
I have this:
+-- feedme@1.0.0
| +-- clarinet@0.11.0
| +-- eventyoshi@0.1.8
| `-- sax@1.2.2

runninf on node v6.9.5

**Comment by fent** [comment]
Still not getting an error :/

This is the test I'm running, `file2` points to a file with the contents of the above url

       fs.createReadStream(file2).pipe(new FeedMe()).on('end', done);

**Comment by elafargue** [comment]
Same here - crashes on anything that is not a valid RSS feed, and apparently no way to catch the error, makes Node crash hard with no 'error' event generated..

`        http.get(url, function(res) {
            var feedparser = new FeedMe();
            feedparser.on('error', function(err) {
                debug('Error:', err);
            });
            feedparser.on('item', function(item) {
                self.titles.push(item.title);
                // Start the news feed
                if (self.titles.length == 2)
                    self.displayNextTitle();
            });
            res.pipe(feedparser);
        }).on('error', function(err) {
            debug('Error getting feed', url);
            self.feedLastFetchedAt = 0; // This will force a retry next time.
            self.cleanup();
        });
`

**Comment by fent** [comment]
Fixed this in new released version 1.1.2
