### ISSUE TITLE
Error: status code 301     at ClientRequest.<anonymous> (src\rss_feeds\rss_feeds.controller.ts:38:23)

### ISSUE THREAD

**Issue by rohitgaidhane** [fent/feedme.js#38]
getting this error 
Error: status code 301
    at ClientRequest.<anonymous> (F:\rohit work\repopushnotifications\pushnotificationsqualzzbackend\src\rss_feeds\rss_feeds.controller.ts:38:23)

/////////////////////////////////////////////////////
code I am using nest.js node js frame work
`@Get('/rss')
async GetFeeds() {
  console.log("abc");
    http.get('http://www.npr.org/rss/rss.php?id=1001', (res:any) => {
      if (res.statusCode != 200) {
        console.error(new Error(`status code ${res.statusCode}`));
        return;
      }
      let parser = new FeedMe();
      parser.on('title', (title:any) => {
        console.log('title of feed is', title);
      });
      parser.on('item', (item:any) => {
        console.log();
        console.log('news:', item.title);
        console.log(item.description);
      });
      res.pipe(parser);
    },(err:any)=>{
console.log(err);
    });
   }`

**Comment by fent** [comment]
301 is a redirect code. the http(s) modules don't provide automatic redirection, for that, use something like [miniget](https://github.com/fent/node-miniget) or [feedsub](https://github.com/fent/node-feedsub)

i'll update the readme
