### ISSUE TITLE
item description returns an object

### ISSUE THREAD

**Issue by gedaiu** [fent/feedme.js#5]
If there is a tag like this, inside a rss item, it is parsed as an empty object not as an empty string

<description />

**Comment by fent** [comment]
There's no definite way to turn an RSS item into a JSON object. Should a tag with nothing in it be represented as an empty object, an empty string, or null?

**Comment by gedaiu** [comment]
I don't know... but from the readme examples I understood that I will always have a string there... and there were a validation error in an app that I wrote because sometimes there was an object. Anyway... I don't think that returning an object it's a good solution, if it's not documented...

**Comment by gedaiu** [comment]
thx!
