### ISSUE TITLE
[doc] end of parsing event + remote url

### ISSUE THREAD

**Issue by kachkaev** [fent/feedme.js#7]
I've tried to use the library for fetching a remote url, but failed setting up the stream correctly. An example with such a case might be useful for future users. Here is one the things I tried:

```js
import FeedMe from 'feedme';
import request from 'request';

const extractedData = [];
const feedUrl = 'http://example.com/feed.rss';
const feedParser = new FeedMe(true);

feedParser.on('item', (feedItem) => {
   // push a new object to extractedData
    console.log('item');
});
feedParser.on('end', () => {
    // save extractedData
    console.log('end');
});

request(feedUrl).pipe(feedParser);
```

For some reason, the output is always the following:
```
end
item
item
...
```

Could you please provide the right way of fetching the feed remotely? I imagine this case is used more often than the one with a local ```fs```.

**Comment by fent** [comment]
Strange that the events are out of order. Just tried something similar to your example, and I get the `item` events before the `end`.

**Comment by kachkaev** [comment]
Thanks for a quick reply @fent!

Were you trying ```request(xxx)``` or something else? Could you please provide some example with remote file fetching and ```end``` event?

**Comment by fent** [comment]
I tried `http`, and also `request`

```js
var http = require('http');
var FeedMe = require('..');

var url = 'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml';
var parser = new FeedMe(false);

parser.on('item', function() {
  console.log('item');
});

parser.on('end', function() {
  console.log('end');
});

http.get(url, function(res) {
  res.pipe(parser);
});
```

**Comment by kachkaev** [comment]
Ah. It seems that the problem may be in the execution times for ```item``` and ```end```. The pipe is probably quickly firing several events one after another, and ```console.log('end')``` is called earlier since ```end``` is simpler to execute. But I may be wrong.

Would it be possible to have some callback after all other callbacks have finished executing?

**Comment by fent** [comment]
If you look at the source for this, `.emit()` is called right away synchronously. It isn't deferred or queued up or anything.

**Comment by fent** [comment]
Did you ever figure this out?

**Comment by kachkaev** [comment]
No. I could not find the way to emit some event strictly after all other callbacks have completed.

**Comment by fent** [comment]
Can I see your exact code?

**Comment by kachkaev** [comment]
Never mind. I've already re-implemented what I wanted with another RSS-reading library.
